jobs:
  include:
    - language: python
      python: 3.8
      before_install:
      - cd backend
      install: 
      - pip install -r requirements.txt
      script:
      - pylint app.py --exit-zero
      - pytest testing.py
