jobs:
  include:
    - language: python
      python: 3.8
      install: 
      - pip install Flask
      - pip install flask_cors
      - pip install flask_pymongo
      - pip install coverage
      - pip install pylint
      script:
      - cd frontend
      - pylint app.py

    - language: node_js
      node_js: 12
      script:
      - node -e "console.log('Hi from NodeJS!')"
