jobs:
  include:
    - language: python
      python: 3.8
      install: 
      - pip install Flask
      - pip install flask_cors
      - pip install flask_pymongo
      - pip install coverage
      - pip install pylint
      script:
      - cd frontend
      - ls
