jobs:
  include:
    - language: python
      python: 3.8
      before_install:
      - cd backend
      install: 
      - pip install -r requirements.txt
      script:
      - pylint app.py --exit-zero
      - pytest testing.py
    - language: node_js
      node_js: 12
      before_install:
      - cd frontend
      install:
      - npm install
      script:
      - npx prettier .
